version: '3.4'
services:
  backend:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .docker.flaskenv
  postgres:
    image: "postgres:9.6-alpine"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .docker.flaskenv
volumes:
  pgdata:
