version: '3.4'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .flaskenv.dev
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
  postgres:
    image: "postgres:9.6-alpine"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .flaskenv.dev
volumes:
  pgdata:
